"""
app/api/routes/outreach.py — Outreach message generator.
POST /api/v1/outreach/generate
"""
import structlog
from fastapi import APIRouter
from pydantic import BaseModel, Field
from app.dependencies import DB, CurrentUser

logger = structlog.get_logger(__name__)
router = APIRouter(prefix="/api/v1/outreach", tags=["Outreach"])

class OutreachRequest(BaseModel):
    company: str = Field(..., min_length=1, max_length=255)
    role: str = Field(..., min_length=1, max_length=255)
    signal_context: str | None = None
    jd_url: str | None = Field(default=None, max_length=2000)
    jd_text: str | None = Field(default=None, max_length=20000)
    tone: str = Field(default="confident", pattern=r"^(confident|formal|casual)$")

@router.post("/generate", summary="Generate outreach messages")
async def generate_outreach(payload: OutreachRequest, current_user: CurrentUser, db: DB) -> dict:
    from app.services.profile.profile_service import ProfileService
    svc = ProfileService(db)
    profile = await svc.get_active_profile_orm(str(current_user.id))
    profile_summary = ""
    if profile:
        pd = profile.to_prompt_dict()
        profile_summary = f"Headline: {pd.get('headline', '')}\nContext: {pd.get('global_context', '')}\n"
        for exp in pd.get("experiences", [])[:3]:
            profile_summary += f"\n{exp.get('role', '')} at {exp.get('company', '')}\n"
    if not profile_summary.strip():
        profile_summary = (
            f"Name: {current_user.full_name or 'Professional'}\n"
            f"Target role: {payload.role}\n"
            f"Target company: {payload.company}\n"
            f"Background: Senior professional exploring opportunities.\n"
        )

    # Resolve JD text: use provided text, or fetch from URL
    jd_text = ""
    if payload.jd_text and payload.jd_text.strip():
        jd_text = payload.jd_text.strip()
    elif payload.jd_url and payload.jd_url.strip():
        try:
            from app.services.jd.extractor import JDExtractor
            import asyncio
            extractor = JDExtractor()
            jd_text = await extractor.extract(payload.jd_url.strip())
        except Exception as e:
            logger.warning("outreach_jd_fetch_failed", url=payload.jd_url, error=str(e))

    # Build richer context from JD + signal
    strategy_memo = ""
    hiring_hypothesis = payload.signal_context or f"Opportunity at {payload.company} for {payload.role}"
    if jd_text:
        strategy_memo = f"JOB DESCRIPTION:\n{jd_text[:6000]}"
        if not payload.signal_context:
            hiring_hypothesis = f"{payload.company} is hiring for {payload.role}. Full JD provided."

    from app.services.shadow.shadow_service import ShadowGenerator
    generator = ShadowGenerator()
    outreach = generator.generate_outreach(
        company=payload.company, hypothesis_role=payload.role,
        hiring_hypothesis=hiring_hypothesis,
        strategy_memo=strategy_memo, profile_summary=profile_summary, tone=payload.tone,
    )
    return {
        "company": payload.company,
        "role": payload.role,
        "tone": payload.tone,
        "linkedin_note": outreach.linkedin_note,
        "cold_email": outreach.cold_email,
        "follow_up": outreach.follow_up,
        "_disclaimer": (
            "These messages were generated by AI based on the information provided. "
            "StealthRole has not verified that this company exists, is actively hiring, "
            "or that the signal context is accurate. Always verify company details "
            "before sending outreach."
        ),
        "_company_verified": False,
    }
